apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: fleetline
resources:
  - namespace.yaml
  - config.yaml
  - migrate.yaml
  - api.yaml
  - gateway.yaml
  - processor.yaml
  - ingress.yaml
images:
  - name: fleetline
    newName: ghcr.io/nonsmiie/fleetline
    newTag: latest
