async (page) => {
  const origin = 'http://127.0.0.1:8097';
  const evidence = process.env.FLEET_EVIDENCE_DIR || './evidence/ui/';
  const run = Date.now().toString(36);
  const owner = `ui-${run}`, other = `other-${run}`, device = `ui-micro-${run}`;
  const results = { utc: new Date().toISOString(), mode: 'actual served files, no source route overlay', run };
  await page.unrouteAll({ behavior: 'wait' });
  await page.context().unrouteAll({ behavior: 'wait' });
  await page.setViewportSize({ width: 1440, height: 1000 });
  await page.goto(`${origin}/?user=${owner}`);
  await page.waitForFunction(() => document.getElementById('status-label')?.textContent === 'Connected');
  const seed = `ui-seed-${run}`;
  const seeded = await page.request.post(`${origin}/locations`, { data: { device_id: seed, latitude: 56.9496, longitude: 24.1052, timestamp: new Date().toISOString() } });
  if (seeded.status() !== 200) throw new Error(`Seed report failed: ${seeded.status()}`);
  await page.waitForFunction((id) => positions.has(id), seed);
  const second = await page.context().newPage();
  const outsider = await page.context().newPage();
  let zoneId;
  try {
    await second.goto(`${origin}/?user=${owner}`);
    await outsider.goto(`${origin}/?user=${other}`);
    await second.waitForFunction(() => document.getElementById('status-label').textContent === 'Connected');
    await outsider.waitForFunction(() => document.getElementById('status-label').textContent === 'Connected');
    await page.locator('.fleet-row').first().focus();
    const focusedId = await page.evaluate(() => document.activeElement.querySelector('strong')?.textContent);
    await page.waitForTimeout(2100);
    results.keyboard_focus_preserved = await page.evaluate((id) => document.activeElement.classList.contains('fleet-row') && document.activeElement.querySelector('strong')?.textContent === id, focusedId);
    if (!results.keyboard_focus_preserved) throw new Error('Fleet refresh lost keyboard focus');
    await page.locator('.fleet-row').first().click();
    results.inspector_open = await page.locator('#inspector').isVisible();
    await page.getByRole('button', { name: 'Close device inspector' }).click();
    await page.getByRole('button', { name: 'Geofences', exact: true }).first().click();
    results.tab_pressed = await page.locator('[data-view="zones"]').getAttribute('aria-pressed') === 'true';
    await page.getByRole('button', { name: 'Add zone', exact: true }).click();
    await page.locator('#name').fill(`QA depot ${run}`);
    await page.locator('#latitude').fill('57.5');
    await page.locator('#longitude').fill('25.5');
    await page.locator('#radius').fill('250');
    await page.locator('#save-zone').click();
    await page.waitForFunction(() => document.getElementById('zone-editor').hidden);
    await second.waitForFunction((name) => document.getElementById('zones').textContent.includes(name), `QA depot ${run}`);
    const zones = await (await page.request.get(`${origin}/geozones`, { headers: { 'X-User-ID': owner } })).json();
    zoneId = zones.items.find((z) => z.name === `QA depot ${run}`).id;
    const prefix = new Date().toISOString().slice(0, 19);
    for (const [suffix, latitude] of [['000100', 57.5], ['000900', 57.5002]]) {
      const response = await page.request.post(`${origin}/locations`, { data: { device_id: device, latitude, longitude: 25.5, timestamp: `${prefix}.${suffix}Z` } });
      if (response.status() !== 200) throw new Error(`Report failed: ${response.status()}`);
    }
    await page.waitForFunction((id) => alertFeed.filter((item) => item.device_id === id).length === 2, device);
    await second.waitForFunction((id) => alertFeed.filter((item) => item.device_id === id).length === 2, device);
    await page.waitForFunction((id) => positions.get(id)?.latitude === 57.5002, device);
    results.owner_sessions_receive_alerts = true;
    results.microsecond_ordering = await page.evaluate((id) => ({ latitude: positions.get(id).latitude, timestamp: positions.get(id).timestamp }), device);
    results.other_user_private = await outsider.evaluate(() => ({ alerts: alertTotal, zones: zones.size }));
    if (results.other_user_private.alerts || results.other_user_private.zones) throw new Error('Private information reached another user');
    await page.locator('.zone-row').getByRole('button', { name: 'Edit', exact: true }).click();
    await page.locator('#name').fill(`QA renamed ${run}`);
    await page.locator('#save-zone').click();
    await second.waitForFunction((name) => document.getElementById('zones').textContent.includes(name), `QA renamed ${run}`);
    await page.locator('.zone-row').getByRole('button', { name: 'Pause', exact: true }).click();
    await second.waitForFunction(() => document.getElementById('zones').textContent.includes('Paused'));
    await page.locator('.zone-row').getByRole('button', { name: 'Resume', exact: true }).click();
    await second.waitForFunction(() => document.getElementById('zones').textContent.includes('Active'));
    results.cross_session_zone_changes = true;
    await page.locator('.zone-row .delete-button').click();
    await page.locator('.zone-row .delete-button').click();
    await second.waitForFunction(() => zones.size === 0);
    zoneId = null;
    results.zone_delete = true;
    await page.getByRole('button', { name: 'Add zone', exact: true }).click();
    await page.locator('#name').fill('Draft only');
    await page.keyboard.press('Escape');
    await page.keyboard.press('/');
    results.search_shortcut_after_escape = await page.locator('#fleet-search').evaluate((node) => node === document.activeElement);
    if (!results.search_shortcut_after_escape) throw new Error('Slash did not focus search after closing the editor');
    await page.getByRole('button', { name: 'Brief', exact: true }).click();
    await page.waitForFunction(() => document.getElementById('insights').textContent.includes('Reporting in the last minute'));
    results.real_brief = true;
    results.assistant_status = await page.locator('#assistant-status').innerText();
    await page.getByRole('button', { name: 'Fleet', exact: true }).click();
    await page.evaluate(() => map.setView([56.9496, 24.1052], 14));
    await page.locator('#fleet-search').blur();
    results.desktop = await page.evaluate(() => ({ width: innerWidth, scroll_width: document.documentElement.scrollWidth, devices: positions.size, fleet_rows: document.querySelectorAll('.fleet-row').length, canvas: document.querySelectorAll('.fleet-canvas').length, utc: new Date().toISOString() }));
    await page.screenshot({ path: `${evidence}served-desktop-${run}.png`, fullPage: true });
    await page.setViewportSize({ width: 390, height: 844 });
    results.mobile = await page.evaluate(() => ({ width: innerWidth, scroll_width: document.documentElement.scrollWidth, utc: new Date().toISOString() }));
    await page.screenshot({ path: `${evidence}served-mobile-${run}.png`, fullPage: true });
    if (results.desktop.width !== results.desktop.scroll_width || results.mobile.width !== results.mobile.scroll_width) throw new Error('Horizontal overflow');
    results.screenshots = [`${evidence}served-desktop-${run}.png`, `${evidence}served-mobile-${run}.png`];
    return results;
  } finally {
    if (zoneId) await page.request.delete(`${origin}/geozones/${zoneId}`, { headers: { 'X-User-ID': owner } });
    await second.close();
    await outsider.close();
  }
}
